"""a2a: 基于 herdr 的多智能体编排框架。

当前有:herdr 调用层(HerdrClient)、启动命令构造(launcher)、拓扑(含动态修改和热加载)、
身份与注册表、Router、持久队列与审计日志、投递引擎、Broker、操作员裁定、agent 生命周期、命令行 `a2a`。
"""
from .errors import (
    HerdrAgentBlocked,
    HerdrAgentNameTaken,
    HerdrAgentNotReady,
    HerdrBinaryNotFound,
    HerdrError,
    HerdrInvalidAgentName,
    HerdrNotFound,
    HerdrPromptFailed,
    HerdrPromptStalled,
    HerdrServerNotRunning,
    HerdrTimeout,
    HerdrUsageError,
)
from .herdr_client import (
    AGENT_STATUSES,
    READY_OR_BLOCKED,
    READY_STATUSES,
    Created,
    HerdrClient,
    session_delete,
    session_list,
    herdr_version,
    session_stop,
)
from .identity import (
    AgentIdentity,
    IdentityError,
    IdentityMismatchError,
    NodeNotInTopologyError,
    SenderNotRegisteredError,
    SenderNotRunningError,
    identity_env,
    resolve_sender,
)
from .launcher import LauncherError, build_launch_command, preflight_launcher
from .audit import AuditLog
from .messages import ALLOWED_TRANSITIONS, Message, can_transition
from .paths import (
    PathConfigError,
    default_audit_path,
    default_registry_path,
    default_spool_dir,
    default_topology_path,
    state_dir,
)
from .registry import (
    AgentAlreadyRegisteredError,
    AgentNotRegisteredError,
    AgentRecord,
    AmbiguousPaneError,
    Registry,
    RegistryError,
    RuntimeAddressConflictError,
)
from .broker import Broker, BrokerAlreadyRunning
from .delivery import DeliveryEngine
from .lifecycle import Lifecycle, LifecycleError
from .policy import BrokerConfig, VERIFIED_HERDR_VERSIONS, classify_prompt_result, semantics_verified
from .router import Router, SendReceipt, SendRejected, session_from_env
from .spool import (IllegalTransitionError, InvalidIdError, MessageNotFoundError, QueueHead, QueueStateError,
                    SlotError, Spool, SpoolError)
from .topology import Edge, RoleSpec, Topology, TopologyError, TopologyStore

__all__ = [
    "AgentAlreadyRegisteredError",
    "AgentIdentity",
    "AgentNotRegisteredError",
    "ALLOWED_TRANSITIONS",
    "AgentRecord",
    "AuditLog",
    "AmbiguousPaneError",
    "Edge",
    "IdentityError",
    "IdentityMismatchError",
    "NodeNotInTopologyError",
    "PathConfigError",
    "Registry",
    "RegistryError",
    "RoleSpec",
    "RuntimeAddressConflictError",
    "SenderNotRegisteredError",
    "SenderNotRunningError",
    "Topology",
    "TopologyError",
    "TopologyStore",
    "IllegalTransitionError",
    "InvalidIdError",
    "MessageNotFoundError",
    "Message",
    "Router",
    "SendReceipt",
    "SendRejected",
    "Spool",
    "SpoolError",
    "QueueHead",
    "QueueStateError",
    "SlotError",
    "can_transition",
    "default_audit_path",
    "default_registry_path",
    "default_spool_dir",
    "session_from_env",
    "default_topology_path",
    "identity_env",
    "resolve_sender",
    "state_dir",
    "AGENT_STATUSES",
    "READY_OR_BLOCKED",
    "READY_STATUSES",
    "Created",
    "HerdrAgentBlocked",
    "HerdrAgentNameTaken",
    "HerdrAgentNotReady",
    "HerdrBinaryNotFound",
    "HerdrClient",
    "HerdrError",
    "HerdrInvalidAgentName",
    "HerdrNotFound",
    "HerdrPromptFailed",
    "HerdrPromptStalled",
    "BrokerConfig",
    "DeliveryEngine",
    "Lifecycle",
    "LifecycleError",
    "Broker",
    "BrokerAlreadyRunning",
    "VERIFIED_HERDR_VERSIONS",
    "classify_prompt_result",
    "semantics_verified",
    "herdr_version",
    "HerdrServerNotRunning",
    "HerdrTimeout",
    "HerdrUsageError",
    "LauncherError",
    "build_launch_command",
    "preflight_launcher",
    "session_delete",
    "session_list",
    "session_stop",
]
